/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bibd.tubespbo.view.manager.panels;

import com.bibd.tubespbo.Di;
import com.bibd.tubespbo.data.model.PembelianModel;
import com.bibd.tubespbo.data.model.ProductModel;
import com.bibd.tubespbo.util.Formatter;
import com.bibd.tubespbo.util.Statics;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * @author HP VICTUS
 */
public class MenuApprovePembelian extends javax.swing.JPanel {

    /**
     * Creates new form MenuApprovePembelian
     */

    private DefaultTableModel tablePembelianModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //super.isCellEditable(row, column);
        }

    };
    private TableRowSorter<DefaultTableModel> tablemPembelianSorter = new TableRowSorter<>(tablePembelianModel);

    ArrayList<String> statusPembelian = new ArrayList<>(
            Arrays.asList(
                    Statics.PEMBELIAN_STATUS_RUNNING,
                    Statics.PEMBELIAN_STATUS_REJECTED,
                    Statics.PEMBELIAN_STATUS_FINNISH,
                    Statics.PEMBELIAN_STATUS_PENDING
            )
    );

    public MenuApprovePembelian() {
        initComponents();

        setupCbActionPembelian();
        setupTablePembelian();
        populateTablePembelian();
    }

    private void setupCbActionPembelian() {
        cbActionPembelian.removeAllItems();
        for (String status : statusPembelian) {
            cbActionPembelian.addItem(status);
        }
    }

    private void resetField() {
        Di.approvePembelianPresenter.resetSelected();
        // reset all field
        tfIdPembelian.setText("");
        tfEntriesDataPembelian.setText("");
        tfTanggalPembelian.setText("");

    }

    private void clearTable() {
        for (int i = tablePembelianModel.getRowCount() - 1; i >= 0; i--) {
            tablePembelianModel.removeRow(i);
        }
    }

    private void populateTablePembelian() {
        clearTable();
        Di.approvePembelianPresenter.getListPembelian(tfIdPembelian.getText());


        clearTable();

        for (PembelianModel pembelian : Di.approvePembelianPresenter.listPembelian) {
            String[] row = {
                    String.valueOf(pembelian.getIdPembelian()),
                    pembelian.getWarehouse(),
                    pembelian.getTanggalOrder().toString(),
                    Formatter.formatRupiah(pembelian.getTotalBiaya()),
                    pembelian.getStatus()
            };
            tablePembelianModel.addRow(row);
        }
    }

    private void setupTablePembelian() {
        tDataPembelian.setModel(tablePembelianModel);
        tDataPembelian.setRowSorter(tablemPembelianSorter);
        tablePembelianModel.addColumn("idPembelian");
        tablePembelianModel.addColumn("Warehouse");
        tablePembelianModel.addColumn("TanggalPembelian");
        tablePembelianModel.addColumn("TotalBiaya");
        tablePembelianModel.addColumn("Status");

        tDataPembelian.getTableHeader().setReorderingAllowed(false);
        tablemPembelianSorter.setSortable(0, false);
        tablemPembelianSorter.setSortable(1, false);
        tablemPembelianSorter.setSortable(2, false);
        tablemPembelianSorter.setSortable(3, false);
        tablemPembelianSorter.setSortable(4, false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDataPembelian = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        bCariIdPembelian = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfIdPembelian = new javax.swing.JTextField();
        tfEntriesDataPembelian = new javax.swing.JTextField();
        bEntriesDataPembelian = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbActionPembelian = new javax.swing.JComboBox<>();
        bSimpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfTanggalPembelian = new javax.swing.JTextField();
        tfTotalBiaya = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Show");

        tDataPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idPembelian", "NamaPembeli", "TanggalPembelian", "TotalBiaya", "Status"
            }
        ));
        jScrollPane1.setViewportView(tDataPembelian);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("APPROVE DATA PEMBELIAN");

        bCariIdPembelian.setBackground(new java.awt.Color(153, 255, 255));
        bCariIdPembelian.setText("Cari");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cari Pembelian");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Total Biaya");

        tfEntriesDataPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEntriesDataPembelianActionPerformed(evt);
            }
        });

        bEntriesDataPembelian.setBackground(new java.awt.Color(153, 255, 255));
        bEntriesDataPembelian.setText("Entries");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("MENU > APPROVE PEMBELIAN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Aksi");

        bSimpan.setBackground(new java.awt.Color(153, 255, 153));
        bSimpan.setText("Simpan");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("TanggalPembelian:");

        tfTanggalPembelian.setEnabled(false);

        tfTotalBiaya.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(bCariIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbActionPembelian, 0, 119, Short.MAX_VALUE)
                                    .addComponent(bSimpan)
                                    .addComponent(tfTanggalPembelian)
                                    .addComponent(tfTotalBiaya))
                                .addGap(137, 137, 137)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfEntriesDataPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bEntriesDataPembelian)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCariIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfEntriesDataPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEntriesDataPembelian))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfTanggalPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbActionPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(bSimpan)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfEntriesDataPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEntriesDataPembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEntriesDataPembelianActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCariIdPembelian;
    private javax.swing.JButton bEntriesDataPembelian;
    private javax.swing.JButton bSimpan;
    private javax.swing.JComboBox<String> cbActionPembelian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tDataPembelian;
    private javax.swing.JTextField tfEntriesDataPembelian;
    private javax.swing.JTextField tfIdPembelian;
    private javax.swing.JTextField tfTanggalPembelian;
    private javax.swing.JTextField tfTotalBiaya;
    // End of variables declaration//GEN-END:variables
}
