/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bibd.tubespbo.view.manager.panels;

import com.bibd.tubespbo.Di;
import com.bibd.tubespbo.data.model.*;
import com.bibd.tubespbo.util.Formatter;
import com.bibd.tubespbo.util.Statics;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.ArrayList;
import java.util.Arrays;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 * @author HP VICTUS
 */
public class MenuApprovePembelian extends javax.swing.JPanel {

    /**
     * Creates new form MenuApprovePembelian
     */

    private DefaultTableModel tablePembelianModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //super.isCellEditable(row, column);
        }

    };
    private TableRowSorter<DefaultTableModel> tablemPembelianSorter = new TableRowSorter<>(tablePembelianModel);

    ArrayList<String> statusPembelian = new ArrayList<>(
            Arrays.asList(
                    Statics.PEMBELIAN_STATUS_RUNNING,
                    Statics.PEMBELIAN_STATUS_REJECTED,
                    Statics.PEMBELIAN_STATUS_FINNISH,
                    Statics.PEMBELIAN_STATUS_PENDING
            )
    );

    public MenuApprovePembelian() {
        initComponents();

        setupCbActionPembelian();
        setupTablePembelian();
        populateTablePembelian();
    }

    private void setupCbActionPembelian() {
        cbActionPembelian.removeAllItems();
        for (String status : statusPembelian) {
            cbActionPembelian.addItem(status);
        }
    }

    private void resetField() {
        Di.approvePembelianPresenter.resetSelected();
        // reset all field
        tfTanggalPembelian.setText("");
        tfTotalBiaya.setText("");
        tfIdPembelian.setText("");
        tfWarehousePembelian.setText("");
        cbActionPembelian.setSelectedIndex(0);

    }

    private void clearTable() {
        for (int i = tablePembelianModel.getRowCount() - 1; i >= 0; i--) {
            tablePembelianModel.removeRow(i);
        }
    }

    private void populateTablePembelian() {
        clearTable();
        Di.approvePembelianPresenter.getListPembelian(tfSearchPembelian.getText());

        for (PembelianModel pembelian : Di.approvePembelianPresenter.listPembelian) {
            String[] row = {
                    String.valueOf(pembelian.getIdPembelian()),
                    pembelian.getAddresWarehouse(),
                    pembelian.getTanggalOrder().toString(),
                    Formatter.formatRupiah(pembelian.getTotalBiaya()),
                    pembelian.getStatus()
            };
            tablePembelianModel.addRow(row);
        }
    }

    private void setupTablePembelian() {
        tDataPembelian.setModel(tablePembelianModel);
        tDataPembelian.setRowSorter(tablemPembelianSorter);
        tablePembelianModel.addColumn("idPembelian");
        tablePembelianModel.addColumn("Warehouse");
        tablePembelianModel.addColumn("TanggalPembelian");
        tablePembelianModel.addColumn("TotalBiaya");
        tablePembelianModel.addColumn("Status");

        tDataPembelian.getTableHeader().setReorderingAllowed(false);
        tablemPembelianSorter.setSortable(0, false);
        tablemPembelianSorter.setSortable(1, false);
        tablemPembelianSorter.setSortable(2, false);
        tablemPembelianSorter.setSortable(3, false);
        tablemPembelianSorter.setSortable(4, false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tDataPembelian = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        bCariIdPembelian = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfSearchPembelian = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbActionPembelian = new javax.swing.JComboBox<>();
        bSimpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfTanggalPembelian = new javax.swing.JTextField();
        tfTotalBiaya = new javax.swing.JTextField();
        btnClearField = new javax.swing.JButton();
        tfIdPembelian = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfWarehousePembelian = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblDetaulSelectedPembelian = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaDetailPemb = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        tDataPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idPembelian", "NamaPembeli", "TanggalPembelian", "TotalBiaya", "Status"
            }
        ));
        tDataPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDataPembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tDataPembelian);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("APPROVE DATA PEMBELIAN");

        bCariIdPembelian.setBackground(new java.awt.Color(153, 255, 255));
        bCariIdPembelian.setText("Cari");
        bCariIdPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariIdPembelianActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cari Pembelian");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Total Biaya");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("MENU > APPROVE PEMBELIAN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Aksi");

        bSimpan.setBackground(new java.awt.Color(153, 255, 153));
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("TanggalPembelian:");

        tfTanggalPembelian.setEnabled(false);

        tfTotalBiaya.setEnabled(false);

        btnClearField.setText("Clear");
        btnClearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldActionPerformed(evt);
            }
        });

        tfIdPembelian.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("IdPembelian");

        tfWarehousePembelian.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Warehouse");

        lblDetaulSelectedPembelian.setText("Detail Pembelian ");

        jLabel11.setText("Product Name - Qty - Total");

        textAreaDetailPemb.setColumns(20);
        textAreaDetailPemb.setRows(5);
        textAreaDetailPemb.setEnabled(false);
        jScrollPane4.setViewportView(textAreaDetailPemb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSearchPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bCariIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(lblDetaulSelectedPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnClearField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bSimpan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbActionPembelian, 0, 119, Short.MAX_VALUE)
                                            .addComponent(tfTanggalPembelian)
                                            .addComponent(tfTotalBiaya))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfWarehousePembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(87, 87, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSearchPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCariIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDetaulSelectedPembelian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTanggalPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWarehousePembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbActionPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearField)
                    .addComponent(bSimpan))
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCariIdPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariIdPembelianActionPerformed

        populateTablePembelian();
    }//GEN-LAST:event_bCariIdPembelianActionPerformed

    private void tDataPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDataPembelianMouseClicked
        int row = tDataPembelian.getSelectedRow();

        int idPembelian = Integer.parseInt(tDataPembelian.getValueAt(row, 0).toString());

        Di.approvePembelianPresenter.selectDataPembelian(
                idPembelian
        );
        PembelianModel selectedPembelian = Di.approvePembelianPresenter.selectedPembelian;
        tfIdPembelian.setText(String.valueOf(selectedPembelian.getIdPembelian()));
        tfWarehousePembelian.setText(selectedPembelian.getAddresWarehouse());
        tfTotalBiaya.setText(Formatter.formatRupiah(selectedPembelian.getTotalBiaya()));
        tfTanggalPembelian.setText(selectedPembelian.getTanggalOrder().toString());
        cbActionPembelian.setSelectedItem(selectedPembelian.getStatus());

        textAreaDetailPemb.setText("");
        for(OrderDetailsModel itemDetail : Di.approvePembelianPresenter.detailPembelian){
            // show the detail of selected pembelian
            // product name, price, and qty
            // show all the data in one label, separated by new line
            textAreaDetailPemb.setText(
//                    "("+itemDetail.getIdProduct()+") - "+
                            textAreaDetailPemb.getText() + itemDetail.getProductName() + " - " +  itemDetail.getJumlah()+ " - " +itemDetail.getTotalPrice() + "\n"
            );
        }
        
    }//GEN-LAST:event_tDataPembelianMouseClicked

    private void btnClearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldActionPerformed
        resetField();
    }//GEN-LAST:event_btnClearFieldActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        Di.approvePembelianPresenter.updateStatusPembelian(
                cbActionPembelian.getSelectedItem().toString()
        );

        if(Di.approvePembelianPresenter.statusUpdatePembelian == -2){
            showMessageDialog(null, "Pilih data pembelian terlebih dahulu");
            return;
        }
        if(Di.approvePembelianPresenter.statusUpdatePembelian == -1){
            showMessageDialog(null, "Gagal update data pembelian");
            return;
        }
        showMessageDialog(null, "Berhasil update data pembelian");
        populateTablePembelian();
        resetField();
    }//GEN-LAST:event_bSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCariIdPembelian;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton btnClearField;
    private javax.swing.JComboBox<String> cbActionPembelian;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDetaulSelectedPembelian;
    private javax.swing.JTable tDataPembelian;
    private javax.swing.JTextArea textAreaDetailPemb;
    private javax.swing.JTextField tfIdPembelian;
    private javax.swing.JTextField tfSearchPembelian;
    private javax.swing.JTextField tfTanggalPembelian;
    private javax.swing.JTextField tfTotalBiaya;
    private javax.swing.JTextField tfWarehousePembelian;
    // End of variables declaration//GEN-END:variables
}
