/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bibd.tubespbo.view.supervisor.supervisorpanels;

import com.bibd.tubespbo.Di;
import com.bibd.tubespbo.data.model.CustomerModel;
import com.bibd.tubespbo.data.model.EmployeeModel;
import com.bibd.tubespbo.data.model.WarehouseModel;
import com.bibd.tubespbo.util.Validator;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP VICTUS
 */
public class MenuCrudCustomer extends javax.swing.JPanel {

    /**
     * Creates new form MenuCrudCustomer
     */
    public MenuCrudCustomer() {
        initComponents();
        setupTableCustomer();
        populateTableCustomer();
    }

    private void populateTableCustomer() {
        Di.manageCustomerPresenter.getAllCustomer(tfIdCustomerSearch.getText());

        clearTable();

        for (CustomerModel custModel : Di.manageCustomerPresenter.customerList) {
            String[] row = {
                String.valueOf(custModel.getIdCustomer()),
                custModel.getNama(),
                custModel.getNoHp(),
                custModel.getAlamat(),
                custModel.getEmail()
            };
            tableCustomerModel.addRow(row);
        }
    }

    private void setupTableCustomer() {
        tblCustomer.setModel(tableCustomerModel);
        tableCustomerModel.addColumn("IdCustomer");
        tableCustomerModel.addColumn("Nama");
        tableCustomerModel.addColumn("NoHp");
        tableCustomerModel.addColumn("Alamat");
        tableCustomerModel.addColumn("Email");
        tblCustomer.getTableHeader().setReorderingAllowed(false);
        tblCustomer.setRowSorter(tableCustomerSorter);

        tableCustomerSorter.setSortable(0, false);
        tableCustomerSorter.setSortable(1, false);
        tableCustomerSorter.setSortable(2, false);
        tableCustomerSorter.setSortable(3, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdCustomer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNamaCustomer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNoHpCustomer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfEmailCustomer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tfIdCustomerSearch = new javax.swing.JTextField();
        bCariIdCustomer = new javax.swing.JButton();
        bTambahDataCustomer = new javax.swing.JButton();
        btnUpdateCust = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        bBersihkan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamatcustomer = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CREATE, UPDATE AND DELETE CUSTOMER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("IdCustomer:");

        tfIdCustomer.setEnabled(false);
        tfIdCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdCustomerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("NoHP:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Alamat:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Email:");

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdCustomer", "Nama", "NoHp", "Alamat", "Email"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cari Customer");

        bCariIdCustomer.setBackground(new java.awt.Color(153, 255, 255));
        bCariIdCustomer.setText("Cari");
        bCariIdCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariIdCustomerActionPerformed(evt);
            }
        });

        bTambahDataCustomer.setBackground(new java.awt.Color(153, 255, 153));
        bTambahDataCustomer.setText("Tambah");
        bTambahDataCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahDataCustomerActionPerformed(evt);
            }
        });

        btnUpdateCust.setBackground(new java.awt.Color(153, 255, 255));
        btnUpdateCust.setText("Update");
        btnUpdateCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("MENU  >  CRUD CUSTOMER");

        bBersihkan.setText("Bersihkan");
        bBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBersihkanActionPerformed(evt);
            }
        });

        taAlamatcustomer.setColumns(20);
        taAlamatcustomer.setRows(5);
        jScrollPane2.setViewportView(taAlamatcustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bTambahDataCustomer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdateCust)
                                        .addGap(73, 73, 73))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfIdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tfEmailCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tfNamaCustomer, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfNoHpCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(bBersihkan)
                                .addGap(133, 133, 133)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(432, 432, 432)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfIdCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(bCariIdCustomer))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfIdCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCariIdCustomer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfIdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNamaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfNoHpCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmailCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateCust)
                            .addComponent(bTambahDataCustomer))
                        .addGap(18, 18, 18)
                        .addComponent(bBersihkan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private DefaultTableModel tableCustomerModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //super.isCellEditable(row, column);
        }

    };
    private TableRowSorter<DefaultTableModel> tableCustomerSorter = new TableRowSorter<>(tableCustomerModel);

    private void bTambahDataCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahDataCustomerActionPerformed
        CustomerModel cm = new CustomerModel();

        String nama = tfNamaCustomer.getText();
        String email = tfEmailCustomer.getText();
        String noHp = tfNoHpCustomer.getText();
        String alamst = taAlamatcustomer.getText();


        if(!formIsValid()){
            return;
        }


        cm.setNama(nama);
        cm.setEmail(email);
        cm.setNoHp(noHp);
        cm.setAlamat(alamst);

        Di.manageCustomerPresenter.addNewCustomer(cm);

        int result = Di.manageCustomerPresenter.statusAddNewCust;
        if (result < 0) {
            System.out.println("Error ");
            return;
        }
        JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan !");
        Di.manageCustomerPresenter.resetManageCustomer();
        resetFields();
        populateTableCustomer();  
    }//GEN-LAST:event_bTambahDataCustomerActionPerformed

    private void bCariIdCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariIdCustomerActionPerformed

        populateTableCustomer();        // TODO add your handling code here:
    }//GEN-LAST:event_bCariIdCustomerActionPerformed

    private void tfIdCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdCustomerActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked

        int row = tblCustomer.getSelectedRow();

        int idCustomer = Integer.parseInt(tableCustomerModel.getValueAt(row, 0).toString());

        Di.manageCustomerPresenter.setSelectedCustomer(
                idCustomer
        );
        CustomerModel selectedCustomer = Di.manageCustomerPresenter.selectedDataCustomer;

        tfIdCustomer.setText(String.valueOf(idCustomer));
        tfNamaCustomer.setText(selectedCustomer.getNama());
        tfEmailCustomer.setText(selectedCustomer.getEmail());
        tfNoHpCustomer.setText(selectedCustomer.getNoHp());
        taAlamatcustomer.setText(selectedCustomer.getAlamat());
        
        bTambahDataCustomer.setEnabled(false);
        btnUpdateCust.setEnabled(true);

    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnUpdateCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustActionPerformed
        CustomerModel cm = Di.manageCustomerPresenter.selectedDataCustomer;

        String nama = tfNamaCustomer.getText();
        String email = tfEmailCustomer.getText();
        String noHp = tfNoHpCustomer.getText();
        String alamst = taAlamatcustomer.getText();

        if (!formIsValid()) {
            return;
        }

        cm.setNama(nama);
        cm.setEmail(email);
        cm.setNoHp(noHp);
        cm.setAlamat(alamst);

        Di.manageCustomerPresenter.updateDataCustomer();

        int result = Di.manageCustomerPresenter.statusUpdateCustomer;
        if (result < 0) {
            System.out.println("Error ");
            return;
        }
        JOptionPane.showMessageDialog(null, "Data Berhasil Di Update !");
//        Di.manageEmployeePresenter.resetSelectedDataEmployee();
//        resetField();
        populateTableCustomer();            // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCustActionPerformed

    private void bBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBersihkanActionPerformed
        resetFields();
    }//GEN-LAST:event_bBersihkanActionPerformed

    private boolean formIsValid() {
        boolean valid = false;
        if (!Validator.isValidEmail(tfEmailCustomer.getText())) {
            JOptionPane.showMessageDialog(null, "Email Tidak Valid!");
            return valid;
        }
        if (tfNamaCustomer.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh kosong !");
            return valid;
        }

        if (tfNoHpCustomer.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "No HP Tidak Boleh kosong !");
            return valid;
        }

        if (taAlamatcustomer.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh kosong !");
            return valid;
        }
        return !valid;
    }

    public void clearTable() {
        for (int i = tableCustomerModel.getRowCount() - 1; i >= 0; i--) {
            tableCustomerModel.removeRow(i);
        }

    }

    private void resetFields() {
        Di.manageCustomerPresenter.resetManageCustomer();
        tfIdCustomer.setText("");
        tfNamaCustomer.setText("");
        tfNoHpCustomer.setText("");
        taAlamatcustomer.setText("");
        tfEmailCustomer.setText("");
        bTambahDataCustomer.setEnabled(true);
        btnUpdateCust.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBersihkan;
    private javax.swing.JButton bCariIdCustomer;
    private javax.swing.JButton bTambahDataCustomer;
    private javax.swing.JButton btnUpdateCust;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taAlamatcustomer;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField tfEmailCustomer;
    private javax.swing.JTextField tfIdCustomer;
    private javax.swing.JTextField tfIdCustomerSearch;
    private javax.swing.JTextField tfNamaCustomer;
    private javax.swing.JTextField tfNoHpCustomer;
    // End of variables declaration//GEN-END:variables
}
